package orders

import (
	"github.com/johnfercher/maroto/v2/pkg/components/col"
	"github.com/johnfercher/maroto/v2/pkg/components/line"
	"github.com/johnfercher/maroto/v2/pkg/components/row"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/props"
)

func (os *OrderService) buildPDFFooter() []core.Row {
	return []core.Row{
		row.New(1).Add(
			line.NewCol(12, props.Line{
				Thickness:   0.3,
				Color:       colorBorder,
				SizePercent: 100})),
		row.New(8).Add(
			col.New(8).Add(
				text.New("Generated by OrderDesk",
					props.Text{Size: 7, Color: colorMuted, Top: 3})),
			col.New(4).Add(
				text.New("© all rights reserved to OrderDesk",
					props.Text{Size: 7, Align: align.Right, Color: colorMuted, Top: 3})),
		)}
}
