// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Company struct {
	ID        int32
	Name      string
	Email     string
	DeletedAt sql.NullTime
}

type CompanyUser struct {
	ID          int32
	CompanyID   int32
	UserID      int32
	RoleID      int32
	DisplayName string
	JoinedAt    sql.NullTime
}

type Invite struct {
	ID        int32
	Email     string
	CompanyID int32
	RoleID    int32
	Token     string
	InvitedBy sql.NullInt32
	CreatedAt sql.NullTime
	ExpiresAt time.Time
}

type Order struct {
	ID         int32
	SupplierID int32
	CompanyID  int32
	UserID     int32
	CreatedAt  time.Time
}

type OrderItem struct {
	ID           int32
	OrderID      int32
	ProductID    int32
	CompanyID    int32
	Quantity     int32
	NameAtOrder  string
	PriceAtOrder sql.NullString
}

type Permission struct {
	ID         int32
	Permission string
}

type Product struct {
	ID         int32
	Name       string
	SupplierID int32
	CompanyID  int32
	Price      sql.NullString
	DeletedAt  sql.NullTime
}

type Role struct {
	ID   int32
	Name string
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
}

type Supplier struct {
	ID        int32
	Name      string
	Email     string
	DeletedAt sql.NullTime
	CompanyID int32
}

type User struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
	Name      string
}

type UserPermission struct {
	UserID       int32
	PermissionID int32
}
